### ISSUE TITLE
Please create a tag as `laradock/php-fpm:2.2-7.3` on dockerhub

### ISSUE THREAD

**Issue by enomotodev** [laradock/php-fpm#27]
`Dockerfile-73` has been added and `php7.3` has also become GA, so please create a tag as `laradock/php-fpm:2.2-7.3` on dockerhub

**Comment by bestlong** [comment]
https://github.com/laradock/laradock/issues/2004

**Comment by sonnygauran** [comment]
Please create a build and tag for `2.2-7.3` for `laradock/php-fpm`

![97E53053-C97D-457C-9B61-AAABB69663E3](https://user-images.githubusercontent.com/188831/62350170-76f1dd80-b534-11e9-90a6-d2244b08591a.jpeg)

![27D28276-6CFC-49A1-9450-4C540D2C958C](https://user-images.githubusercontent.com/188831/62350171-76f1dd80-b534-11e9-95ca-fe90c76ba060.jpeg)

![68DC5FFD-FBFD-4F40-A608-54D6F5E2EA7D](https://user-images.githubusercontent.com/188831/62350173-778a7400-b534-11e9-858d-7fb9f4a81a96.jpeg)
