### ISSUE TITLE
Add WebP support

### ISSUE THREAD

**Issue by harryhorton** [laradock/php-fpm#32]
Please include support for WebP. Since `docker-php-ext-configure gd` is run in this image before being used by Laradock's php-fpm docker image within the repo, it'd be helpful to include webp as an option here.

This is what I reran in the other dockerfile to get webp support added.
```# Install the PHP gd library
RUN docker-php-ext-configure gd \
  --enable-gd-native-ttf \
  --with-jpeg-dir=/usr/lib \
  --with-webp-dir=/usr/lib \
  --with-freetype-dir=/usr/include/freetype2 && \
  docker-php-ext-install gd```

**Comment by qiuyuhome** [comment]
Please add `--with-webp-dir=/usr/lib`.

**Comment by Trixpua** [comment]
Any news about this issue?

**Comment by tmtung144** [comment]
up
