### ISSUE TITLE
[question] Using the latest and stable tags

### ISSUE THREAD

**Issue by andrey-helldar** [laradock/php-fpm#42]
There was a question about tags: why don't you use stable and / or latest tags when publishing an image?

I use this image when developing, but each time I manually go into the repository and see if a new version has appeared, it is a dubious pleasure.

**Comment by bestlong** [comment]
add latest tag is ok, is done.
about stable, i think current number version should be considered.

**Comment by andrey-helldar** [comment]
@bestlong, close the issue or leave?
