### ISSUE TITLE
memory leak - issue latest build

### ISSUE THREAD

**Issue by lionslair** [laradock/php-fpm#46]
I added wkhtmltopdf to the php-fpm image today. Did a rebuild and thought all was fine. 

However soon as a browser visited any site the ram on the system went through the roof until the point where I ram out and the system crashed.
I have followed all the steps. 

* Rebuild my images multiple times
* docker-compose down
* docker container prune
* docker image prune -a
* docker volume prune

and brought up all the containers again.  The container that is having the issue each and every time is the laradock-php-fpm container.

I am right now attempting to use this image instead https://hub.docker.com/layers/laradock/php-fpm/2.7-7.4/images/sha256-59b3b2b936e16fb2b6ec7d818a84bcc3bd23b068be0e710dcdf05e5fc20d095d?context=explore will report if it works. Something with https://hub.docker.com/layers/laradock/php-fpm/latest-7.4/images/sha256-c1943c4a18d0903f70c444a33e4dcf806c9269d6566c667e6ccff74ab427673e?context=explore seems to be driving the ram usage through the roof. Nothing else with my setup has changed previous to what I mentioned. Colleague has had the identical issue.

hmm get same issue with https://hub.docker.com/layers/laradock/php-fpm/2.7-7.4/images/sha256-59b3b2b936e16fb2b6ec7d818a84bcc3bd23b068be0e710dcdf05e5fc20d095d?context=explore

**Comment by tjventurini** [comment]
Having the same issue I think. Since Friday my freshly build php-fpm containers in my laradock setup eat up my memory when I make a reaquest to the instance. Sometimes happen inside the workspace too ...

**Comment by tjventurini** [comment]
Tried to fix this all night. I'm on Ubuntu 20.04 (but also tried 20.10) and can't make it work. 

The problem is appearing since Friday for me. That's when I set up my computer with a fresh copy of ubuntu. First I thought something wen't wrong during the installation but I just set it up again and it's not working anymore.

I'm using  `Docker version 19.03.14, build 5eb3275d40` and `docker-compose version 1.17.1, build 6d101fb`.

The repo I'm trying to set up is https://github.com/tjventurini/laravel-blueprint so you might get the issue when you run then setup.

Not sure what else I can provide you by now. It's not writing any logs or so.

Any help is appreciated, this one is driving me crazy! 🆘

**Comment by lionslair** [comment]
I found my issue after 12 hours of hell. It was xdebug. disabled and rebuild and that solved my issue

**Comment by tjventurini** [comment]
Thx, that solved my issue too. Although I now have to find out how I can make use of xdebug again.

**Comment by Vinimaks** [comment]
Any updates @tjventurini ?

**Comment by Bahramn** [comment]
I hade the same issue, It seems xdebug in version 3 needs a different config, It's my xdebug.ini file which I'm using and it's working properly:
```
; Old Xdebug Docker configuration
; https://serversforhackers.com/c/getting-xdebug-working
;xdebug.remote_enable=1
;xdebug.remote_handler=dbgp
;xdebug.remote_port=9000
;xdebug.remote_autostart=1
;xdebug.remote_connect_back=0
;xdebug.remote_idekey=phpstorm
;xdebug.remote_host=host.docker.internal

; New Xdebug Docker configuration
; https://xdebug.org/docs/upgrade_guide
; https://xdebug.org/docs/all_settings#mode
xdebug.mode=debug,trace
; https://xdebug.org/docs/step_debug
; https://xdebug.org/docs/all_settings#discover_client_host
xdebug.discover_client_host=true
; https://xdebug.org/docs/all_settings#client_discovery_header
xdebug.client_discovery_header=HTTP_XDCB
; https://xdebug.org/docs/all_settings#client_host
; in linux it doesn't work on docker 19 version, because of domain name
xdebug.client_host=host.docker.internal
; https://xdebug.org/docs/all_settings#client_port
xdebug.client_port=9003
; https://xdebug.org/docs/all_settings#start_with_request
xdebug.start_with_request=default

; https://xdebug.org/docs/all_settings#var_display_max_data
;xdebug.var_display_max_data=512
; https://xdebug.org/docs/all_settings#var_display_max_depth
;xdebug.var_display_max_depth=3
; https://xdebug.org/docs/all_settings#var_display_max_children
;xdebug.var_display_max_children=128
; https://xdebug.org/docs/all_settings#cli_color
;xdebug.cli_color=1
; https://xdebug.org/docs/all_settings#show_local_vars
;xdebug.show_local_vars=0
; https://xdebug.org/docs/all_settings#dump_globals
;xdebug.dump_globals=true
; https://xdebug.org/docs/all_settings#dump_once
;xdebug.dump_once=true
; https://xdebug.org/docs/all_settings#dump_undefined
;xdebug.dump_undefined=false;
; https://xdebug.org/docs/all_settings#dump.*
;xdebug.dump.SERVER=REMOTE_ADDR,REQUEST_METHOD
;xdebug.dump.GET=*
;xdebug.dump.POST=*
; https://xdebug.org/docs/all_settings#file_link_format
;xdebug.file_link_format =
; https://xdebug.org/docs/all_settings#filename_format
;xdebug.filename_format = ...%s%n
; https://xdebug.org/docs/all_settings#max_stack_frames
;xdebug.max_stack_frames=-1
; https://xdebug.org/docs/all_settings#show_local_vars
;xdebug.show_local_vars=0
; https://xdebug.org/docs/all_settings#show_error_trace
;xdebug.show_error_trace=0
; https://xdebug.org/docs/all_settings#show_exception_trace
;xdebug.show_exception_trace=0

```

**Comment by rahilwazir** [comment]
For me it was to remove the `develop` mode

```
xdebug.mode=debug
```

**Comment by iulianwebdev** [comment]
> For me it was to remove the `develop` mode
> 
> ```
> xdebug.mode=debug
> ```

This worked for me as well
