### ISSUE TITLE
M1 chip support

### ISSUE THREAD

**Issue by kju196** [laradock/php-fpm#54]
Could you build the images support M1 chip (arm platform)?
I faced up ```mmap() failed: [12] Cannot allocate memory``` problem with linux/amd64 images.

**Comment by aramean** [comment]
Hi! Is this fixed?

**Comment by bestlong** [comment]
Hi @aramean 

I don't have Apple M1 device to confirm.

Ref. https://github.com/laradock/workspace/issues/47

Seems to be OK.
