### ISSUE TITLE
Dockerfile for PHP 7.1 - oci runtime error

### ISSUE THREAD

**Issue by robbydooo** [laradock/php-fpm#9]
I have pulled the Dockerfile-71 down locally as it is not yet available from laradock directly and modified the docker-compose file to use it. I did a docker-compose build php-fpm.

When i run:

    docker-compose up -d nginx redis mysql

I am getting the following error:

```
Creating network "laradock_default" with the default driver
Creating laradock_redis_1
Creating laradock_applications_1
Creating laradock_workspace_1
Creating laradock_php-fpm_1

ERROR: for php-fpm  Cannot start service php-fpm: oci runtime error: container_linux.go:247: starting container process caused "chdir to cwd (\"/var/www/html\") set in config.json failed: no such file or directory"
ERROR: Encountered errors while bringing up the project.
```

Any Ideas? I am not sure which config.json it is referring to.

**Comment by sid606** [comment]
same here

**Comment by progsmile** [comment]
The same problem, with separate php:7-fpm

**Comment by demjanich** [comment]
You need to change WORKDIR (because in php-fpm default WORKDIR is /var/www/html) in your php-fpm Dockerfile, in this way:

FROM php:fpm
WORKDIR /var/www

**Comment by 0uro** [comment]
> You need to change WORKDIR (because in php-fpm default WORKDIR is /var/www/html) in your php-fpm Dockerfile, in this way:
> 
> FROM php:fpm
> WORKDIR /var/www
